import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{createClient,Session}from'@supabase/supabase-js';
import'./style.css';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
type Opp={id:string;title:string;stage:string;opportunity_score:number|null;confidence_score:number|null;data_quality_score:number|null;company_id:string;contact_id?:string|null};
type GuardState={decision:string;reason:string;at:string};

function App(){
 const[session,setSession]=useState<Session|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[tenant,setTenant]=useState<any>(null),[opps,setOpps]=useState<Opp[]>([]),[busy,setBusy]=useState(false),[guards,setGuards]=useState<Record<string,GuardState>>({});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load();else{setTenant(null);setOpps([])}},[session]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false)}
 async function load(){setError('');const{data:m,error:me}=await supabase.from('tenant_members').select('tenant_id,role,tenants(id,name,slug)').limit(1).single();if(me){setError(me.message);return}setTenant(m);const{data,error}=await supabase.from('opportunities').select('id,title,stage,opportunity_score,confidence_score,data_quality_score,company_id,contact_id').order('created_at',{ascending:false});if(error)setError(error.message);else setOpps(data||[])}
 function explain(decision:string,o:Opp){if(decision==='review')return 'Validation humaine requise avant toute action externe.';if(decision==='block'&&!o.contact_id)return 'Action bloquée : contact ou donnée de contact manquante.';if(decision==='block')return 'Action bloquée par les règles de sécurité, consentement ou permissions.';return 'Action autorisée par Orixeo Guard.'}
 async function guard(o:Opp){if(!tenant)return;if(!o.contact_id){setGuards(g=>({...g,[o.id]:{decision:'block',reason:'Action bloquée : contact manquant.',at:new Date().toISOString()}}));return}const{data,error}=await supabase.rpc('guard_outreach',{p_tenant:tenant.tenant_id,p_contact:o.contact_id,p_agent:'sales',p_action:'external.send'});if(error){setGuards(g=>({...g,[o.id]:{decision:'error',reason:error.message,at:new Date().toISOString()}}));return}const d=String(data).toLowerCase();setGuards(g=>({...g,[o.id]:{decision:d,reason:explain(d,o),at:new Date().toISOString()}}))}
 if(!session)return <main className="login"><section><div className="brand">ORIXEO <b>LAB</b></div><h1>Control Center</h1><p>Votre équipe IA opérationnelle.</p><form onSubmit={login}><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Mot de passe" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy}>{busy?'Connexion…':'Se connecter'}</button></form>{error&&<div className="err">{error}</div>}</section></main>;
 return <div><header><div className="brand">ORIXEO <b>LAB</b></div><div>{tenant?.tenants?.name||'Chargement…'} · {tenant?.role}<button className="link" onClick={()=>supabase.auth.signOut()}>Déconnexion</button></div></header><main className="wrap"><div className="hero"><div><span className="tag">CONTROL CENTER · V0.2</span><h1>Pilotage des opportunités</h1><p>Scoring, Orixeo Guard et validation humaine avant toute action externe.</p></div><button onClick={load}>Actualiser</button></div>{error&&<div className="err">{error}</div>}<div className="cards"><article><strong>{opps.length}</strong><span>Opportunités</span></article><article><strong>{opps.filter(o=>o.stage==='scored').length}</strong><span>Scorées</span></article><article><strong>{opps.filter(o=>(o.opportunity_score||0)>=70).length}</strong><span>Prioritaires ≥70</span></article></div><section className="panel"><h2>Opportunity Engine</h2><div className="table"><div className="row head"><span>Opportunité</span><span>Étape</span><span>Score</span><span>Confiance</span><span>Qualité</span><span>Guard</span></div>{opps.map(o=>{const g=guards[o.id];return <React.Fragment key={o.id}><div className="row"><span>{o.title}</span><span className="pill">{o.stage}</span><span>{o.opportunity_score??'—'}</span><span>{o.confidence_score??'—'}</span><span>{o.data_quality_score??'—'}</span><span>{g?<span className={'guard '+g.decision}>{g.decision.toUpperCase()}</span>:<button className="small" onClick={()=>guard(o)}>Tester</button>}</span></div>{g&&<div className="guardDetail"><strong>{g.decision.toUpperCase()}</strong><span>{g.reason}</span><button className="ghost" onClick={()=>guard(o)}>Retester</button></div>}</React.Fragment>})}</div></section></main></div>
}
createRoot(document.getElementById('root')!).render(<App/>);